# Generated by Django 3.0.7 on 2020-06-19 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('customer_xid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('reference_id', models.UUIDField(unique=True)),
                ('withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.WalletUser')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField()),
                ('disabled_at', models.DateTimeField()),
                ('balance', models.FloatField()),
                ('owned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.WalletUser')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('reference_id', models.UUIDField(unique=True)),
                ('deposited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.WalletUser')),
            ],
        ),
    ]
