# Generated by Django 3.0.7 on 2020-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
